### ISSUE TITLE
Development documentation

### ISSUE THREAD

**Issue by flaviut** [sk1project/sk1-wx#144]
Is there any documentation on how to get started with writing patches to this program? I'm primarily interested in uc2, so I've done the following and it's seemed to work so far:

1. create a virtualenv using `virtualenv -p python2 env` and then enter it using `source env/bin/activate`
2. run `./setup-uc2.py build` to compile C extensions
3. copy the C extensions from `build/` into their original directories in `src/`
4. run `pip install Pillow==5.2.0 pycairo==1.17.1` to install dependencies
5. run `./uc2-launcher.py` to launch the program

Is there a better way to do this?

**Comment by sk1project** [comment]
Expected way is:

1. Clone project from github: ``git clone https://github.com/sk1project/sk1-wx <you_project_folder>``
2. Install project dependencies from README.txt
3. Run ``python setup-uc2.py build_update`` - this will compile native extensions and copy them into project source tree
4. Open project folder in PyCharm (Community version). Now you are ready to develop :)

BTW: the best way to test new code from sk1 application because UI app is better for that. If you need code tracing, use logger, but not ``print`` statement. sK1 has a good built-in log viewer for these purposes.
