### ISSUE TITLE
Problem with UI elements: transparent background color, on different GTK theme

### ISSUE THREAD

**Issue by maxim-s-barabash** [sk1project/sk1-wx#225]
Adwaita
![output_1](https://user-images.githubusercontent.com/2724325/63647755-b88a3880-c72e-11e9-9a99-169a21b8ac85.gif)
Ambiance
![output_2](https://user-images.githubusercontent.com/2724325/63647792-19197580-c72f-11e9-9da5-0e004ffb7a19.gif)

![Screenshot from 2019-08-25 11-56-22](https://user-images.githubusercontent.com/2724325/63647825-7281a480-c72f-11e9-8eca-288d1f03c090.png)

I think we need to redefine the background color of widgets

**Comment by unixino** [comment]
Could it be a fixed stand alone theme that doesn't depend on the operating system them ?

**Comment by sk1project** [comment]
The issue is not reproducable on Ubuntu Gnome 18.04 + Adwaita theme. Looks like custom modified theme.

**Comment by sk1project** [comment]
Ubuntu Gnome 19.04 - application works as expected. The issue is not reproduced. It seems the problem cause is a videocard driver. Try to update it from manufacturer website.
![Screenshot from 2019-08-25 22-03-55](https://user-images.githubusercontent.com/13432939/63654575-dda99600-c784-11e9-951f-dafaeb63deb1.png)
