### ISSUE TITLE
Package in AUR

### ISSUE THREAD

**Issue by francois072** [sk1project/sk1-wx#260]
Just tried to install the package from the AUR but that failed.
Manually compiling the program also didn't work when using the file with the PKGBUILD.
The appimage doesn't want to launch.

**Comment by Joermungand** [comment]
As you complained on AUR, the package’s failure to build was caused by your connection to GitHub timing out. If manual compilation of the PKGBUILD using `makepkg` failed for any reason other the the connection timing out you should post the error messages, so I know what they are about. However, since this is not related to sK1 itself, but to compiling the PKGBUILD, I suggest taking this discussion to [AUR](https://aur.archlinux.org/packages/sk1-git). I’m not sure what appimage you are talking about; in AUR, you compile your packages from source using `makepkg` with the PKGBUILD script.

**Comment by francois072** [comment]
Appimage: https://github.com/probonopd/sk1-wx/releases/tag/continuous

arch linux package from Sk1project.net: 
Output:
`[francois@francois-pc Downloads]$ makepkg -s
==> Making package: sk1 2.0rc4-1 (Sun 07 Jun 2020 04:34:01 PM SAST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found sk1-2.0rc4_20190525.tar.gz
==> Validating source files with md5sums...
    sk1-2.0rc4_20190525.tar.gz ... Skipped
==> Extracting sources...
  -> Extracting sk1-2.0rc4_20190525.tar.gz with bsdtar
==> Starting build()...
chmod: cannot access '/home/francois/Downloads/src/sk1-2.0rc4/setup.cfg_sk1': Permission denied
chmod: cannot access '/home/francois/Downloads/src/sk1-2.0rc4/src': Permission denied
chmod: cannot access '/home/francois/Downloads/src/sk1-2.0rc4/utils': Permission denied
chmod: cannot access '/home/francois/Downloads/src/sk1-2.0rc4/dependencies.py': Permission denied
chmod: cannot access '/home/francois/Downloads/src/sk1-2.0rc4/README.txt': Permission denied
chmod: cannot access '/home/francois/Downloads/src/sk1-2.0rc4/setup.cfg': Permission denied
chmod: cannot access '/home/francois/Downloads/src/sk1-2.0rc4/native_mods.py': Permission denied
chmod: cannot access '/home/francois/Downloads/src/sk1-2.0rc4/MANIFEST.in_sk1': Permission denied
chmod: cannot access '/home/francois/Downloads/src/sk1-2.0rc4/PKG-INFO': Permission denied
chmod: cannot access '/home/francois/Downloads/src/sk1-2.0rc4/LICENSE': Permission denied
chmod: cannot access '/home/francois/Downloads/src/sk1-2.0rc4/setup-sk1.py': Permission denied
==> ERROR: A failure occurred in build().
    Aborting...
`

**Comment by Joermungand** [comment]
Oh, I see. Just remove the chmod line in the downloaded PKGBUILD (line 19) and make sure you remove all directories created upon previous compilation attempts. Or try again with pamac; you may get luckier connecting to GitHub.
