### ISSUE TITLE
Please add hotkeys for zoom in/out

### ISSUE THREAD

**Issue by mr-GreyWolf** [sk1project/sk1-wx#283]
Please add hotkeys for zoom in/out.
For example:
**Ctrl** and **+** key = Zoom in
**Ctrl** and **-** key = Zoom out

**Comment by maxim-s-barabash** [comment]
[Wiki sK1 Keyboard-Shortcut-Keys](https://github.com/sk1project/sk1-wx/wiki/Keyboard-Shortcut-Keys)
similar topic https://github.com/sk1project/sk1-wx/issues/267

**Comment by Symbian9** [comment]
> Please add hotkeys for zoom in/out.

@mr-GreyWolf, Actually you may use next:

- <kbd>Shift</kbd> + <kbd>Mouse Wheel Up</kbd> = Zoom In
- <kbd>Shift</kbd> + <kbd>Mouse Wheel Down</kbd> = Zoom Out

**NOTE:** As for now I'm closing this as `duplicate`, because it would be solved after implementing *"Preferences > Keyboard Shortcuts"* settings.

- Follow: https://github.com/sk1project/sk1-wx/issues/239
