### ISSUE TITLE
Inkscape to Uniconvertor: .plt file output scale discrepancy -  UC/Sk1 still inputs at 90dpi?

### ISSUE THREAD

**Issue by 8thrule** [sk1project/sk1-wx#44]
Greetings,

Thank you for the Uniconvertor patches for Inkscape. The recent change in Inkscape to 96dpi may combine with code in Uniconvertor/SK1 to result in output scale issues:

Events:
Successful installation of Inkscape patch files for Uniconvertor.
Successful output of .plt file from Inkscape via Uniconvertor.
**However, scale of .plt file is larger than original... 1:1.06667.** 

Using:
Win 8.1, 64bit, 
Inkscape 0.92.0 r15299 (now has default scale of 96dpi)
Uniconvertor 1.1.5 (most recent, AFAICT)

More info:
https://bugs.launchpad.net/inkscape/+bug/1658260 
Comment  number 18 +

Any insights are greatly appreciated.

Regards,
TD 
tylerdurden (8thrule)

[plotters.zip](https://github.com/sk1project/sk1-wx/files/723842/plotters.zip)

**Comment by raboof** [comment]
With the latest nightly (2.0rc3) converting inkscape svg to plt and then back into Inkscape again also produces a (in my case much) smaller object.

**Comment by jnweiger** [comment]
@sk1project Please note that the dpi default is 96, as per SVG standard. The standard once mentioned 90, but was changed to 96 a few years ago. SVG derives its defaults from the CSS definition https://www.w3.org/TR/CSS21/syndata.html#length-units

@raboof when things are 'much smaller' then you probably ran into a 72dpi vs 96dpi snakepit. Illustrator is the most prominent advocat of 72dpi as a default (due to their very own understanding of standard).

**Comment by sk1project** [comment]
@jnweiger unfortunately we need correctly processing existing SVG files but not to be Inkscape compatible only. Nevertheless we reopen this issue to find better solution than implemented.

**Comment by sk1project** [comment]
@jnweiger @8thrule @raboof we have refactored code related to dpi issue. Now we have dpi auto detection. Nevertheless you may force dpi using `--svg_dpi=...` option. Also to have exact translation result just don't use px as a document unit. Set mm, in, cm etc. and translation will be accurate. This is naturally because cutting plotter doesn't operate with pixels.
